### ISSUE TITLE
Disable tests cases for Alpha4

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-distribution#1481]
**Description:**
Following tests have been disabled due to failures in[ this PR](https://github.com/ballerina-platform/ballerina-distribution/pull/1480). Those are including BBE failures and some other tests

- [x] LengthValidator Tests (This is failed due to kafka and rabbitmq BBEs) https://github.com/ballerina-platform/ballerina-distribution/pull/1482

StdLib tests

- [x] task
- [x] websocket

**BBE build failures**

- [x] http-timeout
- [x] http-retry
- [x] http-failover
- [x] http-load-balancer
- [x] http-circuit-breaker
- [x] content-based-routing
- [x] header-based-routing
- [ ] websocket-basic-sample
- [x] http-1-1-to-2-0-protocol-switch
- [x] http-compression
- [x] http-streaming
- [x] different-payload-types
- [x] http-100-continue
- [x] http-cors
- [x] request-with-multiparts
- [x] http-disable-chunking
- [x] absolute-path-and-path
- [x] http-client-data-binding
- [x] http-redirects
- [x] non-transaction-retry
- [x] local-transactions-with-handlers
- [x] url-encode-decode
- [x] jwt-issue-validate
- [x] crypto
- [x] filepath
- [x] cache
- [x] time
- [x] csv-io
- [x] strings-io
- [x] bytes-io
- [x] async #1494
- [x] worker-interaction #1494
- [x] workers #1494
- [x] error-handling-in-single-place #1496
- [x] fail #1494
- [x] xml-attributes
- [x] streams
- [ ] iterable-objects
- [ ] range-expressions
- [x] raw-template
- [x] any-type
- [x] query-action
- [x] query-expression-to-stream
- [x] error-match-statement
- [x] mapping-match-statement
- [x] tuple-match-statement
- [x] the-main-function
- [x] function-pointers
- [x] hello-world-client
- [x] hello-world-parallel
- [x] hello-world-service

**BBE Output verification failures**

- [x] non-transaction-retry
- [x] url-encode-decode
- [x] xslt-transformation
- [x] task-one-time-job-execution
- [x] task-frequency-job-execution
- [x] strings
- [x] cache
- [x] xml-io
- [x] json-io
- [x] csv-io
- [x] strings-io
- [x] bytes-io
- [x] java-exceptions
- [x] overloaded-methods-constructors
- [x] java-varargs
- [x] java-arrays
- [x] access-mutate-java-fields
- [x] invoke-java-methods
- [x] create-java-objects
- [x] isolated-functions #1494
- [x] isolated-variables #1494
- [x] isolated-objects #1494
- [x] threads-and-strands #1494
- [x] async #1494
- [x] fork #1494
- [x] worker-interaction #1494
- [x] workers #1494
- [x] user-defined-error #1494
- [x] trap #1494
- [x] panic #1494
- [x] check #1494
- [x] fail #1494
- [x] error-handling #1494
- [x] array-binding-pattern #1494
- [x] record-binding-pattern #1494
- [x] tuple-binding-pattern #1494
- [x] xml-functions
- [x] xml-access
- [x] xml-namespaces
- [x] xml-attributes
- [x] xml-literal
- [x] query-expression-to-xml
- [x] query-expression-to-table
- [x] query-expression-to-string
- [x] query-expression-to-stream
- [x] query-expression
- [x] elvis-operator #1497
- [x] type-guard #1497
- [x] type-test-expression #1497
- [x] error-match-statement
- [x] mapping-match-statement
- [x] tuple-match-statement
- [x] match #1497
- [x] if-else #1497
- [x] functional-iteration #1497
- [x] expression-bodied-functions #1497
- [x] closures #1497
- [x] anonymous-functions
- [x] function-pointers
- [x] basic-documentation #1507
- [x] quoted-identifiers #1497
- [x] functions-with-rest-parameter #1497
- [x] functions-with-included-record-parameters #1497
- [x] functions-with-defaultable-parameters #1497
- [x] functions-with-required-parameters #1497
- [x] functions
- [x] var
- [x] variables
- [x] modules
- [x] hello-world-client
- [x] hello-world-parallel
- [x] hello-world

**Comment by niveathika** [comment]
Closing as this is invalid after revamp of bbe
